# Generated by Django 6.1.2 on 2026-10-08 20:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReporteAtencion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="Reporte No.",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="Fecha"
                    ),
                ),
                (
                    "oficina",
                    models.CharField(
                        max_length=150, verbose_name="Oficina o dependencia"
                    ),
                ),
                (
                    "hora_llegada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de llegada"
                    ),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de salida"
                    ),
                ),
                (
                    "persona_afectada",
                    models.CharField(
                        max_length=150, verbose_name="Persona afectada (nombre)"
                    ),
                ),
                (
                    "cargo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Cargo o puesto"
                    ),
                ),
                (
                    "tecnico",
                    models.CharField(
                        max_length=150, verbose_name="Técnico responsable"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Teléfono o extensión"
                    ),
                ),
                (
                    "tipos_problema",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Tipo de problema"
                    ),
                ),
                (
                    "otro_tipo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Otro (especifique)"
                    ),
                ),
                ("descripcion", models.TextField(verbose_name="Descripción")),
                (
                    "resolucion",
                    models.TextField(
                        blank=True, verbose_name="Qué se hizo para solucionarlo"
                    ),
                ),
                (
                    "recomendaciones",
                    models.TextField(
                        blank=True, verbose_name="Para evitar que el problema se repita"
                    ),
                ),
                (
                    "resultado",
                    models.CharField(
                        choices=[
                            ("si", "Sí, quedó resuelto"),
                            ("parcial", "Parcialmente, queda pendiente"),
                            ("no", "No se pudo resolver"),
                        ],
                        default="si",
                        max_length=10,
                        verbose_name="¿Se resolvió el problema?",
                    ),
                ),
                (
                    "motivo_seguimiento",
                    models.TextField(blank=True, verbose_name="Motivo o seguimiento"),
                ),
                (
                    "hubo_compra",
                    models.BooleanField(
                        default=False, verbose_name="¿Fue necesario comprar algo?"
                    ),
                ),
                (
                    "no_factura",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="No. de factura o comprobante",
                    ),
                ),
                (
                    "firma_tecnico",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="Nombre del técnico"
                    ),
                ),
                (
                    "firma_encargado",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Nombre del encargado de oficina",
                    ),
                ),
                (
                    "firma_jefe",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        verbose_name="Nombre del jefe inmediato",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Reporte de atención técnica",
                "verbose_name_plural": "Reportes de atención técnica",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CompraItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "articulo",
                    models.CharField(max_length=150, verbose_name="Artículo comprado"),
                ),
                (
                    "cantidad",
                    models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Precio unit. (Q)"
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compras",
                        to="reportes.reporteatencion",
                    ),
                ),
            ],
        ),
    ]
