# Generated by Django 5.0.1 on 2026-10-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporteatencion',
            name='firma_jefe',
        ),
        migrations.AddField(
            model_name='reporteatencion',
            name='firma_encargado_img',
            field=models.TextField(blank=True, verbose_name='Firma del encargado'),
        ),
        migrations.AddField(
            model_name='reporteatencion',
            name='firma_tecnico_img',
            field=models.TextField(blank=True, verbose_name='Firma del técnico'),
        ),
        migrations.AlterField(
            model_name='compraitem',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reporteatencion',
            name='firma_tecnico',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nombre del técnico que apoyó'),
        ),
        migrations.AlterField(
            model_name='reporteatencion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
